CREATE DATABASE IF NOT EXISTS filmdb;

USE filmdb;

DROP TABLE IF EXISTS filme;
DROP TABLE IF EXISTS genres;

CREATE TABLE filme (
    FilmeID INT AUTO_INCREMENT PRIMARY KEY,
    Titel VARCHAR(255) NOT NULL,
    Altersfreigabe TINYINT,
    Erscheinungsjahr SMALLINT,
    Genre1 VARCHAR(255),
    Genre2 VARCHAR(255),
    Genre3 VARCHAR(255),
    Filmlaenge SMALLINT,
    file TEXT
);

CREATE TABLE genres (
    GenreID INT AUTO_INCREMENT PRIMARY KEY,
    GenreName VARCHAR(255) NOT NULL
);